### ISSUE TITLE
Installation error on ubuntu 22.04 with Vitis/Vivado 2023.1 

### ISSUE THREAD

**Issue by fllay** [Xilinx/KRS#105]
I followed the instruction up to this point

```
sudo ls -l # Hack to give sudo access to shell, else build may hang.
colcon build --merge-install  # about 18 mins in an AMD Ryzen 5 PRO 4650G
```
Then I got the following errors

```/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
--- stderr: ament_acceleration                                                                                                                           
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.5 or higher is required.  You are running version 3.3.2


Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 59, in build
    rc = await extension.build(
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 87, in build
    rc = await self._reconfigure(args, env)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 182, in _reconfigure
    buildfile = get_buildfile(cmake_cache)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 114, in get_buildfile
    if 'Visual Studio' in generator:
TypeError: argument of type 'NoneType' is not iterable
---
Failed   <<< ament_acceleration [0.34s, exited with code 1]
--- stderr: tracetools_image_pipeline
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.5 or higher is required.  You are running version 3.3.2
```

Please help.

**Comment by jasvinderkhurana** [comment]
@fllay 

As mentioned in the documentation you need to use the below command to ensure the cmake version > 3.5

export PATH="/usr/bin":$PATH


See the logs below:

```
source /tools/Xilinx/Vitis/2022.1/settings64.sh
jaswinder@xhdjaswinder40:~$ source /opt/ros/humble/setup.bash
jaswinder@xhdjaswinder40:~$ cmake --version
cmake version 3.3.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
jaswinder@xhdjaswinder40:~$ export PATH="/usr/bin":$PATH
jaswinder@xhdjaswinder40:~$ cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).


```
