### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by tomasthoresen** [Xilinx/KRS#30]
Getting an error when trying to follow the example.

> colcon acceleration select kv260

ros2@ros2-Latitude-E7450:~/krs_ws$ colcon acceleration select kv260
[0.411s] ERROR:colcon:colcon acceleration: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 528, in verb_main
    rc = context.args.main(context=context)
  File "/home/ros2/krs_ws/install/lib/python3.8/site-packages/colcon_acceleration/subverb/select.py", line 57, in main
    firmware_options = get_firmware_options()
  File "/home/ros2/krs_ws/install/lib/python3.8/site-packages/colcon_acceleration/subverb/list.py", line 38, in get_firmware_options
    firmware_options = outs.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by jasvinderkhurana** [comment]
@tomasthoresen , can you please clean your workspace and build again

i.e. delete build, install, log, and acceleration folder in krs_ws, then give the build command

```
colcon build --merge-install
source install/setup.bash
colcon acceleration select kv260

**Comment by jasvinderkhurana** [comment]
@tomasthoresen , Was your issue resolved shall I close the ticket?

**Comment by jasvinderkhurana** [comment]
Closing the ticket!
